apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindspark-backend
  labels:
    app: mindspark-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mindspark-backend
  template:
    metadata:
      labels:
        app: mindspark-backend
    spec:
      containers:
      - name: backend
        image: mindspark-backend:latest
        ports:
        - containerPort: 7001
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:7001"

