apiVersion: v1
kind: Service
metadata:
  name: mindspark-backend-service
  labels:
    app: mindspark-backend
spec:
  type: ClusterIP
  selector:
    app: mindspark-backend
  ports:
  - name: http
    port: 7001
    targetPort: 7001

