apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindspark-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mindspark-backend
  template:
    metadata:
      labels:
        app: mindspark-backend
    spec:
      containers:
      - name: backend
        image: mindspark-backend:latest
        ports:
        - containerPort: 7001
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "https://+:7001"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindspark-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mindspark-frontend
  template:
    metadata:
      labels:
        app: mindspark-frontend
    spec:
      containers:
      - name: frontend
        image: mindspark-frontend:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: BACKEND_URL
          value: "https://mindspark-backend-service:7001"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"