apiVersion: v1
kind: Service
metadata:
  name: mindspark-backend-service
spec:
  type: ClusterIP
  selector:
    app: mindspark-backend
  ports:
  - port: 7001
    targetPort: 7001
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mindspark-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: mindspark-frontend
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
