apiVersion: v1
kind: Service
metadata:
  name: mindspark-service
spec:
  type: NodePort
  selector:
    app: mindspark
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007  # You can pick a port between 30000-32767
