apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindspark-frontend
  labels:
    app: mindspark-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mindspark-frontend
  template:
    metadata:
      labels:
        app: mindspark-frontend
    spec:
      containers:
      - name: frontend
        image: mindspark-frontend:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: BACKEND_URL
          value: "http://mindspark-backend-service:7001"

