apiVersion: v1
kind: Service
metadata:
  name: mindspark-frontend-service
  labels:
    app: mindspark-frontend
spec:
  type: LoadBalancer
  selector:
    app: mindspark-frontend
  ports:
  - name: http
    port: 80
    targetPort: 5000

